# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-16 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=60, unique=True)),
                ('password', models.CharField(max_length=257)),
                ('createTime', models.DateTimeField(auto_now_add=True)),
                ('lastUpdateTime', models.DateTimeField(auto_now=True)),
                ('lastLoginTime', models.DateTimeField(auto_now=True)),
                ('isAdmin', models.BooleanField(default=False)),
                ('regIP', models.CharField(default='', max_length=60)),
            ],
        ),
    ]
